[build]
    base = "frontend"
    command = "bun install && bun run build"
    publish = "frontend/dist"

[functions]
    directory = "frontend/netlify/functions"

[context.production]
    command = "bun install --frozen-lockfile && bun run build"

[context.deploy-preview]
    command = "bun install && bun run build"

[context.branch-deploy]
    command = "bun install && bun run build"
